"use server";

import { auth } from "@/auth";
import connectDB from "@/lib/db";
import Invoice from "@/models/invoice-model";
import Settings from "@/models/settings-model";
import nodemailer from "nodemailer";
import User from "@/models/user-model";
// import { format } from "date-fns";

interface InvoiceItem {
  description: string;
  quantity: number;
  price: number;
}

export async function sendInvoiceEmail(invoiceId: string) {
  const session = await auth();
  if (!session?.user?.id) return { error: "Unauthorized" };

  try {
    await connectDB();

    // ইনভয়েস এবং সেটিংস ডাটা আনা
    const invoice = await Invoice.findById(invoiceId).populate("clientId");
    const settings = await Settings.findOne({ userId: session.user.id });
    
    // ইউজারের প্ল্যান চেক করা
    const user = await User.findById(session.user.id).select("plan");
    const isPro = user?.plan === "pro";

    if (!invoice || !invoice.clientId) return { error: "Invoice or Client not found" };

    const businessName = settings?.businessName || "QuickInvoice User";
    const currency = settings?.currency || "BDT";
    const clientEmail = invoice.clientId.email;
    const clientName = invoice.clientId.name;

    if (!clientEmail) return { error: "Client does not have an email address." };

    // ডিউ ক্যালকুলেশন
    const dueAmount = invoice.totalAmount - invoice.paidAmount;
    const isPaid = invoice.status === 'paid';

    // ইমেইল ট্রান্সপোর্টার কনফিগারেশন
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.SMTP_EMAIL,
        pass: process.env.SMTP_PASSWORD,
      },
    });

    // ১. ব্র্যান্ডিং লজিক (Pro vs Free)
    const brandingHtml = !isPro
      ? `
        <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee;">
          <p style="font-size: 12px; color: #9ca3af; margin: 0;">
            Invoice generated by <a href="https://quickinvoice.com" style="color: #4f46e5; text-decoration: none; font-weight: bold;">QuickInvoice</a>
          </p>
        </div>
      `
      : "";

    // ২. স্ট্যাটাস কালার লজিক
    const statusColor = isPaid ? "#16a34a" : (dueAmount > 0 ? "#dc2626" : "#ca8a04"); // Green, Red, Yellow
    const statusBg = isPaid ? "#dcfce7" : (dueAmount > 0 ? "#fee2e2" : "#fef9c3"); // Light variations

    // ৩. HTML টেমপ্লেট ডিজাইন
    const emailHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
      </head>
      <body style="margin: 0; padding: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f3f4f6; color: #374151;">
        
        <div style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
          
          <div style="background-color: #1f2937; padding: 30px 40px; text-align: center;">
            <h1 style="margin: 0; color: #ffffff; font-size: 24px; font-weight: bold; letter-spacing: 1px;">${businessName}</h1>
          </div>

          <div style="padding: 40px;">
            
            <p style="font-size: 16px; line-height: 1.5; margin-bottom: 20px;">
              Dear <strong>${clientName}</strong>,
            </p>
            <p style="font-size: 16px; line-height: 1.5; color: #4b5563; margin-bottom: 25px;">
              We hope you are doing well. Here is the invoice for our recent services. Please find the details below.
            </p>

            <div style="background-color: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin-bottom: 30px;">
              <div style="display: flex; justify-content: space-between; margin-bottom: 10px;">
                <span style="color: #6b7280; font-size: 14px;">Invoice Number:</span>
                <strong style="color: #111827;">${invoice.invoiceName}</strong>
              </div>
              <div style="display: flex; justify-content: space-between; margin-bottom: 10px;">
                <span style="color: #6b7280; font-size: 14px;">Date:</span>
                <strong style="color: #111827;">${new Date(invoice.date).toDateString()}</strong>
              </div>
              <div style="display: flex; justify-content: space-between; align-items: center;">
                <span style="color: #6b7280; font-size: 14px;">Status:</span>
                <span style="background-color: ${statusBg}; color: ${statusColor}; padding: 4px 12px; border-radius: 99px; font-size: 12px; font-weight: bold; text-transform: uppercase;">
                  ${invoice.status}
                </span>
              </div>
            </div>

            <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px;">
              <thead>
                <tr style="border-bottom: 2px solid #e5e7eb;">
                  <th style="text-align: left; padding: 12px 0; color: #6b7280; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em;">Description</th>
                  <th style="text-align: center; padding: 12px 0; color: #6b7280; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em;">Qty</th>
                  <th style="text-align: right; padding: 12px 0; color: #6b7280; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em;">Price</th>
                </tr>
              </thead>
              <tbody>
                ${invoice.items.map((item: InvoiceItem) => `
                  <tr style="border-bottom: 1px solid #f3f4f6;">
                    <td style="padding: 16px 0; color: #374151; font-size: 14px;">${item.description}</td>
                    <td style="padding: 16px 0; text-align: center; color: #374151; font-size: 14px;">${item.quantity}</td>
                    <td style="padding: 16px 0; text-align: right; color: #374151; font-weight: 500; font-size: 14px;">${item.price}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>

            <div style="border-top: 2px solid #e5e7eb; padding-top: 20px; text-align: right;">
              <p style="margin: 0 0 10px 0; font-size: 14px; color: #6b7280;">Total Amount: <span style="color: #111827; font-weight: 600;">${currency} ${invoice.totalAmount}</span></p>
              
              ${dueAmount > 0 
                ? `<div style="display: inline-block; background-color: #fee2e2; border: 1px solid #fecaca; padding: 10px 20px; border-radius: 6px; margin-top: 10px;">
                     <p style="margin: 0; font-size: 14px; color: #dc2626;">Amount Due</p>
                     <p style="margin: 5px 0 0 0; font-size: 24px; font-weight: bold; color: #b91c1c;">${currency} ${dueAmount.toFixed(2)}</p>
                   </div>`
                : `<p style="color: #16a34a; font-weight: bold; font-size: 18px;">Paid in Full</p>`
              }
            </div>

            <div style="margin-top: 40px; text-align: left;">
              <p style="font-size: 14px; color: #4b5563; margin: 0;">If you have any questions, feel free to reply to this email.</p>
              <p style="font-size: 14px; color: #4b5563; margin-top: 5px;">Thank you for your business!</p>
            </div>

            ${brandingHtml}
          </div>
        </div>
      </body>
      </html>
    `;

    // ইমেইল পাঠানো
    await transporter.sendMail({
      from: `"${businessName}" <${process.env.SMTP_EMAIL}>`,
      to: clientEmail,
      replyTo: settings.email,
      subject: `Invoice #${invoice.invoiceName} from ${businessName}`,
      html: emailHtml,
    });

    return { success: `Invoice sent to ${clientEmail}` };

  } catch (error) {
    console.error(error);
    return { error: "Failed to send email. Check SMTP settings." };
  }
}